### ISSUE TITLE
Design 'Know your 30' tab from the drawer in new activity

### ISSUE THREAD

**Issue by krishnarai30** [IOSD/YFHR_Android_App#14]
Design 'know your 30' tab from ct.docx file provided in the content folder
Create an activity that is pleasing to the eye in the theme colors of blue and white.
Whatsapp +91 9717430033 for clarifications
Put PR with Screenshots

**Comment by SahanMonaara** [comment]
I'll do this.

**Comment by SparshWadhwa** [comment]
@krishnarai30  yeah, I will do it
