### ISSUE TITLE
Design 'Be an educator' tab in the drawer using web view activity within the application

### ISSUE THREAD

**Issue by krishnarai30** [IOSD/YFHR_Android_App#15]
Design 'Be an educator' tab from ct.docx file provided in the content folder
Create an activity that is pleasing to the eye in the theme colors of blue and white.
Whatsapp +91 9717430033 for clarifications
Put PR with Screenshots

**Comment by SahanMonaara** [comment]
Can you assign me to do this?

**Comment by krishnarai30** [comment]
@SahanMonaara OK
