### ISSUE TITLE
Design 'about us' tab from the drawer in a new activity

### ISSUE THREAD

**Issue by krishnarai30** [IOSD/YFHR_Android_App#16]
Design 'about us' tab from ct.docx file provided in the content folder
Create an activity that is pleasing to the eye in the theme colors of blue and white.
Whatsapp +91 9717430033 for clarifications
Put PR with Screenshots

**Comment by darelover** [comment]
I want to do it... Assign this to me

**Comment by krishnarai30** [comment]
@darelover OK

**Comment by darelover** [comment]
pull requested
