### ISSUE TITLE
Design 'Contact us' tab in the drawer in new activity

### ISSUE THREAD

**Issue by krishnarai30** [IOSD/YFHR_Android_App#17]
Design 'contact us' tab from ct.docx file provided in the content folder
Add team image in content folder in this activity in proper scaling at the top
Create an activity that is pleasing to the eye in the theme colors of blue and white.
Whatsapp +91 9717430033 for clarifications
Put PR with Screenshots

**Comment by tavishjain** [comment]
i'll try this one

**Comment by krishnarai30** [comment]
@tavishjain ok
