### ISSUE TITLE
Create Main activity as navgation drawer activity 

### ISSUE THREAD

**Issue by krishnarai30** [IOSD/YFHR_Android_App#6]
With 6 Operations
1. Inter-branch channel (chat)
2-6 name XYZ for now

For 2-6 each activity leads to new empty activity

**Comment by JuanBarros2** [comment]
Can you explain better what do you want?

**Comment by darelover** [comment]
For these 6 operations, do you want to open an new empty activity or a fragment would suffice ??

**Comment by darelover** [comment]
pull requested

**Comment by darelover** [comment]
![screenshot_2017-10-28-22-23-49-324_tech iosd yfhr](https://user-images.githubusercontent.com/25029996/32136644-f166ae66-bc2e-11e7-9082-38c39d1e5426.png)
